services:
  - type: web
    name: ocr-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OCR_ENGINE
        value: tesseract
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://ocr-m6761xzyo-tusharnaugains-projects.vercel.app,http://localhost:3000
    healthCheckPath: /


